sonar.projectKey=zeus058_SE_Writing_Web
sonar.organization=zeus058
sonar.projectName=YAG - Writing Novels Web
sonar.projectVersion=1.0.0
sonar.sources=src/backend/app,src/frontend/src
sonar.tests=src/backend/tests
sonar.exclusions=**/node_modules/**,**/.next/**,**/.venv/**,src/backend/migrations/**
sonar.python.version=3.11
sonar.javascript.environments=browser,node
