sonar.projectKey=zeus058_SE_Writing_Web
sonar.projectName=SE_Writing_Web
sonar.sources=src
sonar.tests=src/backend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/migrations/**,src/backend/tests/**,src/frontend/out/**

sonar.python.version=3.11
sonar.python.coverage.reportPaths=src/backend/coverage.xml
sonar.javascript.lcov.reportPaths=src/frontend/coverage/lcov.info
