import { BarChart, ErrorGuide, LineChart, MetricCard } from "@/components/ui";
import { AppShell } from "@/components/layout";

export function AdminDashboardScreen() {
  return <AppShell activeId="s19"><section className="metric-grid"><MetricCard label="Người dùng mới 7 ngày" value="1.284" change="+12%" /><MetricCard label="Truyện chờ duyệt" value="38" change="Cần xử lý" /><MetricCard label="Doanh thu tháng" value="84M" change="+18%" /><MetricCard label="Vi phạm chờ xử lý" value="7" change="Ưu tiên cao" /></section><section className="action-strip" style={{ marginTop: 24 }}><div><strong>Hệ thống ổn định</strong><div className="list-meta">API phản hồi trung bình 182ms, hàng đợi kiểm duyệt còn 38 chương.</div></div><button className="button" data-toast="Đã làm mới số liệu vận hành.">Làm mới dữ liệu</button></section><section className="layout-right" style={{ marginTop: 24 }}><div className="panel panel-pad"><h2 className="section-title">Doanh thu</h2><LineChart /></div><div className="panel panel-pad stack"><h2 className="section-title">Việc cần xử lý</h2><div className="list"><a className="list-item" href="/content-moderation">5 chương bị gắn cờ<span className="badge badge-red">Cao</span></a><a className="list-item" href="/reports">Xuất báo cáo doanh thu tuần<span className="badge badge-blue">Thường</span></a></div></div></section></AppShell>;
}

export function ModerationScreen() {
  return <AppShell activeId="s20"><section className="layout-right"><main className="panel panel-pad stack"><div className="inline-actions"><select className="select" style={{ width: "auto" }}><option>Tất cả trạng thái</option><option>Cần xem xét</option><option>Đang chờ</option></select><button className="button" data-toast="Danh sách kiểm duyệt đã được lọc.">Lọc</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Chương</th><th>Tác giả</th><th>Lý do AI</th><th>Trạng thái</th><th>Thời gian chờ</th></tr></thead><tbody>{["Bóng Đêm Sau Cửa Sổ", "Lời Hứa Không Tên", "Thành Phố Lặng Im", "Một Ngày Rất Xa"].map((title, index) => <tr key={title}><td>{title}</td><td>{["Linh An", "Hải Đăng", "Lam Tử", "Bảo Châu"][index]}</td><td>{["Bạo lực mô tả chi tiết", "Ngôn từ công kích", "Nghi vấn sao chép nội dung", "Thiếu cảnh báo độ tuổi"][index]}</td><td><span className={`badge ${index === 0 ? "badge-red" : "badge-amber"}`}>{index === 0 ? "Cần xem xét" : "Đang chờ"}</span></td><td>{index + 1} giờ</td></tr>)}</tbody></table></div></main><aside className="panel panel-pad stack"><h2 className="section-title">Nội dung đang duyệt</h2><span className="badge badge-red">AI gắn cờ: bạo lực mô tả chi tiết</span><p className="section-subtitle">Admin có thể duyệt, từ chối kèm lý do hoặc khóa tài khoản nếu vi phạm lặp lại.</p><ErrorGuide title="Nếu quyết định bị hệ thống chặn" items={["Nhập lý do kiểm duyệt tối thiểu 20 ký tự.", "Không khóa tài khoản khi chưa có cảnh báo trước đó.", "Kiểm tra lại lịch sử vi phạm trong hồ sơ tác giả."]} /><button className="button button-success" data-toast="Đã duyệt chương và thông báo cho tác giả.">Duyệt</button><button className="button button-danger" data-toast="Đã từ chối chương." data-toast-type="warning">Từ chối + Gửi cảnh báo</button></aside></section></AppShell>;
}

export function ReportsScreen() {
  return <AppShell activeId="s21"><section className="panel panel-pad stack"><div className="inline-actions" style={{ justifyContent: "space-between" }}><div className="tabs"><button className="tab-button active" data-tab-trigger="revenue">Doanh thu</button><button className="tab-button" data-tab-trigger="users">Người dùng</button><button className="tab-button" data-tab-trigger="content">Nội dung</button></div><div className="inline-actions"><input className="input" style={{ width: "auto" }} defaultValue="01/05/2026 - 18/05/2026" /><button className="button button-primary" data-toast="Đã xuất báo cáo CSV.">Xuất CSV</button></div></div><div className="tab-panel active" data-tab-panel="revenue"><BarChart /></div><div className="tab-panel" data-tab-panel="users"><LineChart /></div><div className="tab-panel" data-tab-panel="content"><BarChart /></div><ErrorGuide title="Không xuất được báo cáo?" items={["Khoảng ngày không được vượt quá 90 ngày.", "Tài khoản cần quyền Admin báo cáo tài chính.", "Thử xuất lại CSV sau khi làm mới dữ liệu dashboard."]} /></section><section className="panel panel-pad" style={{ marginTop: 24 }}><h2 className="section-title">Top tác giả theo lượt đọc và doanh thu chia sẻ</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Tác giả</th><th>Lượt đọc</th><th>Doanh thu chia sẻ</th><th>Trạng thái</th></tr></thead><tbody><tr><td>Linh An</td><td>1.8M</td><td>18.2M</td><td><span className="badge badge-green">Ổn định</span></td></tr><tr><td>Hải Đăng</td><td>1.1M</td><td>11.7M</td><td><span className="badge badge-amber">Cần nhắc lịch</span></td></tr></tbody></table></div></section></AppShell>;
}
