-- =============================================================================
-- Migration: V4__fix_embedding_dimension.sql
-- Description: Fix story_embeddings vector dimension from 1536 to 768.
--   The original schema used vector(1536), but the embedding models actually
--   produce 768-dim vectors (text-embedding-004 → 768, gemini-embedding-001
--   with outputDimensionality=768). All existing embeddings are invalid
--   (generated by the now-shut-down text-embedding-004 model) and will be
--   re-generated on startup by sync_all_missing_embeddings_async.
-- Idempotent: safe to run multiple times.
-- =============================================================================

-- Step 1: Drop the IVFFlat index (it references the old vector dimension)
DROP INDEX IF EXISTS idx_story_embeddings_embedding_cosine;

-- Step 2: Truncate all existing embeddings (they are invalid anyway)
TRUNCATE TABLE story_embeddings;

-- Step 3: Alter the column from vector(1536) to vector(768)
ALTER TABLE story_embeddings
  ALTER COLUMN embedding TYPE vector(768);

-- Step 4: Recreate the IVFFlat cosine index with correct dimension
CREATE INDEX IF NOT EXISTS idx_story_embeddings_embedding_cosine
  ON story_embeddings
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

-- Step 5: Update the comment to reflect the correct model and dimension
COMMENT ON COLUMN story_embeddings.embedding
  IS 'gemini-embedding-001 with outputDimensionality=768; indexed with IVFFlat cosine';
